services:
  db:
    image: postgres:13
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
                      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: olea_fit_development

  olea_fit_api:
    build:
      context: ./backend
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/olea_fit
      - ./backend/tmp:/olea_fit/backend/tmp
      - ./backend/log:/olea_fit/backend/log
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    environment:
      ## https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/
      PIDFILE: /tmp/pids/server.pid
      DATABASE_URL: postgres://postgres:password@db:5432/olea_fit_development
    tmpfs:  
      - /tmp/pids/
