services:
  db:
    image: postgres:13
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: danceter_development

  dance_api:
    build:
      context: ./backend
      args:
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    env_file:
      - .env
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/danceter
      - ./backend/tmp:/danceter/tmp
      - ./backend/log:/danceter/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/danceter_development
      

  # frontend:
  #     build:
  #       context: ./frontend
  #     command: bun run dev
  #     volumes:
  #       - ./frontend:/danceter
  #       - /danceter/node_modules
  #     ports:
  #       - "5173:5173" # Adjust port to match Vite's default or custom port
  #     environment:
  #       NODE_ENV: development
  #     depends_on:
  #       - web