source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.2.1'

gem 'pg', '~> 1.1'

gem 'puma', '~> 6.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'bcrypt', '~> 3.1.7'
gem 'jbuilder'

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem 'image_processing', '~> 1.2'

gem 'base64', '0.2.0'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :development do
  gem 'pry-remote', '~> 0.1.8'
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'listen', '~> 3.8'
  gem 'pry-rails', '~> 0.3.9'
end

gem 'faker', '~> 3.2'
gem 'jwt'
gem 'rubocop', '~> 1.50'
